git:
  depth: 5

stages:
  - "Build and Test"
  - "Package"

jobs:
  include:
  - stage: "Build and Test"
    language: java
    jdk: oraclejdk11
    before_script:
      - cd sample-application-backend
    script:
      - echo "Maven build"
      - echo "Run test coverage and Quality Gate"
  - stage: "Build and Test"
    language: node.js
    node_js: "12.20"
    before_script:
      - cd sample-application-frontend
    script:
      - echo "NPM install and build"
  - stage: "Package"
    before_script:
      - cd sample-application-backend
    script:
      - docker build -t otakouilles/devops_back .
      - echo "Docker build ...".
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "Docker login ..."
      - docker push otakouilles/devops_back
      - echo "Docker push ..."
  - stage: "Package"
    before_script:
      - cd sample-application-frontend
    script:
      - docker build -t otakouilles/devops_front .
      - echo "Docker build ..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "Docker login ..."
      - docker push otakouilles/devops_front
      - echo "Docker push ..."
  - stage: "Build and Test"
    before_script:
      - cd sample-application-backend
    language: java
    script:
      - mvn clean verify "org.jacoco:jacoco-maven-plugin:prepare-agent" "install" "sonar:sonar" "-Dsonar.projectKey=devops-2021"

addons:
  sonarcloud:
    organization: "iliesdevops"
    before_script:
      - cd sample-application-backend
    token: "$SONARCLOUD_TOKEN"

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"
services:
  - docker